### ISSUE TITLE
[Bug] [0.2.0] Engines and panels wont activate inside a warp field

### ISSUE THREAD

**Issue by akman15** [UmbraSpaceIndustries/WarpDrive#11]
When i try to activate an engine and toggle solar panels that are inside the boarder of the warp bubble (even when the warp drive is not activated) i get the message "cant activate while stowed".

**Comment by BobPalmer** [comment]
Does this craft have a cargo or service bay?  Pic please, sounds like it is unrelated to this mod.

**Comment by akman15** [comment]
![screen shot 2015-05-12 at 5 06 53](https://cloud.githubusercontent.com/assets/5766520/7589069/5794b114-f8c9-11e4-8996-ed3ac8d4c05b.png)

**Comment by helaeon** [comment]
Just built an approximation of that ship (looks like you're using KSPx which I'm not using, I am using NF SpaceCraft though)
Solar panels gigantors? If so I was able to get my panels to extend, both manually and with mechjeb

**Comment by BobPalmer** [comment]
Closing as I cannot repro this and expect it's a mod interaction issue.
