### ISSUE TITLE
Warp Engine attach dont work

### ISSUE THREAD

**Issue by MRRadioactiv** [UmbraSpaceIndustries/WarpDrive#17]
Hi - at first thx for your nice Mod :)
but I have two issues with your Mod:
1) I have under "UmbraSpaceIndustries\WarpDrive\Parts" 5 config files (visit pic) - but ingame i have 9 Warp Engines:
![unbenannt-3](https://cloud.githubusercontent.com/assets/12857542/8131462/afef2560-111a-11e5-84f6-b12858f71439.jpg)
I dont understand this - is that "ok" or is there a bug/game problem?!

2) the attachment of the warpengine models dont work right:
![1](https://cloud.githubusercontent.com/assets/12857542/8131497/ee992158-111a-11e5-89f3-cca1ff4b64d5.jpg)
i hope you can help me - if you want to see all mods that i use - i post it here 

PS sorry for my english.

MRRadioactiv

**Comment by futrtrubl** [comment]
Are you using the latest version? 0.21. Because it only has 2 part configs. Remember to delete everything from the relevant folders before upgrading mods.
Edit: Those extra cfgs look like they come from another mod.

**Comment by helaeon** [comment]
Just checked on my game (noticed you were using my ZZZ conversions). I'm getting the right number of parts and the attachment is working fine in my game. You might want to make sure you don't have some extra warp drive .cfgs littered around your GameData folder (like maybe you grabbed the wrong folder when you did an install, so there might be an extra "GameData" or "UmbraSpaceIndustries" folder somewhere. KSP grabs cfgs from anywhere.)

Also that is likely a pre-1.0 version of the mod as the attachment node issue is caused by .90 or earlier mod parts being used in 1.0 or later.

**Comment by MRRadioactiv** [comment]
@futrtrubl  I use the last version /i tryed also a clean mod installation (delete older folder, unzip mod zip...). 
@helaeon if i remove the "WarpDrive" folder - all warpengines are away - if i rename the engines, look like "Alcubierre Drive x (2.5m)", the game dont show this name ingame. The names of the "to much" engines are: (0.625m); (1,25m); (1,875m); (2,5m); (3,75m); (5m) - i tryed also to remove TweakScale - the problem isnt fixed. I dont have any idea where the problem is.

Thx for your support - i hope we find out where the problem is.

my ksp folder:
![3](https://cloud.githubusercontent.com/assets/12857542/8143442/9f91d3b0-11ac-11e5-89b4-75a4a0812129.jpg)

my gamedata folder:
![2](https://cloud.githubusercontent.com/assets/12857542/8143443/af239c0a-11ac-11e5-9899-12f58dc85317.jpg)

**Comment by futrtrubl** [comment]
Then where are the extra configs coming from, because they aren't in the warpdrive zip?

**Comment by MRRadioactiv** [comment]
http://forum.kerbalspaceprogram.com/threads/100798-1-0-2-Alcubierre-Warp-Drive-(Stand-alone)-v0-2-1-2015-05-15/page67
post #669

Or do you mean this strange parts?

**Comment by futrtrubl** [comment]
That's just it, this mod does not contain those files.

**Comment by helaeon** [comment]
@futrtrubl Right, I wrote those cfgs to use ZZZ's models specifically for this (it's why I checked it against my install as I'm using them too. There should be 3 of the same model but 3 different sizes with 3 different configuration setups - I have plans for pushing it along when I do the re-balance of the warp drives here in a bit). It doesn't explain why there are duplicates of the standard USI warp drives.

@MRRadioactiv - would you happen to be using Sophia's Warp Drive mod too? Sophia says it shouldn't be incompatible, but it might be, and suggests using it by itself. I would suggest deleting the WarpDrive folder, then install from RoverDude's latest making sure it loads fine (no duplicates). This will fix your attachment node problem for sure as you have to be on an old version for that to happen. Then if you want to use the ZZZ models too, merge that after you know the main plug-in works.
My next guess is that maybe something with filter extensions? (I'm not using that one so I don't know)

**Comment by MRRadioactiv** [comment]
@helaeon  Sophias Drive?

**Comment by MRRadioactiv** [comment]
i know now what the problem is - this mod and this: http://forum.kerbalspaceprogram.com/threads/111159-WIP-0-90-KSP-Interstellar-Extended
have a problem....i dont know what go wrong - but if i remove the last one - the bug is gone away.
(all work right! - also the attach bug)

//EDIT: now i have a "cannot activate while stowed" problem...

**Comment by helaeon** [comment]
Neither RoverDude or I have been able to replicate the "cannot activate while stowed" issue.  I even re-built a ship someone else posted to see if I could get it to do it and it didn't. I'm thinking it too is an interaction with another mod, maybe even an outdated other mod (firespitter?)

**Comment by MRRadioactiv** [comment]
i try a mod for mod "disable/enable". - ...KSP Interstellar have problems with this Mod (it hide, add this strange engines above - also this strange attach problem)
