### ISSUE TITLE
Increase Prices of warp drives

### ISSUE THREAD

**Issue by NyankoSensei** [UmbraSpaceIndustries/WarpDrive#19]
As Endgame technology the price need to be more hight

MM_WarpDrive.cfg
@PART[USI_WarpDrive]
{
@entryCost *= 10
@Cost *= 10

}

@PART[USI_WarpDrive_625]
{
@entryCost *= 10
@Cost *= 10
}

**Comment by BobPalmer** [comment]
Tweaked in next update
