### ISSUE TITLE
Drive activates on Ship Load even when de-activated prior to switching vessels.

### ISSUE THREAD

**Issue by helaeon** [UmbraSpaceIndustries/WarpDrive#2]
When switching to a vessel equipped with the warp drive, the ship usually loads with drive activated destroying nearby ships and those docked with the ship with the drive.

**Comment by Ristellise** [comment]
i am having the same issue

**Comment by storyd** [comment]
I am having similar issue. 
0.635m inside KSP 1.0 fairing invokes the kracken at launch.
without fairing, launch rocket (outside field) is destroyed.

Startup sound effects fire and top text reads "failsafe: 900km" once kracken subsides and fairings are separated to inspect.

**Comment by BobPalmer** [comment]
Removing the destruction bit as that's causing some other issues, and should also close this issue.
