### ISSUE TITLE
Boost to algorithm efficiency

### ISSUE THREAD

**Issue by helaeon** [UmbraSpaceIndustries/WarpDrive#22]
According to Sophia :
"Every frame, PlayWarpAnimation calls GameObject.FindGameObjectsWithTag("Icon_Hidden") and then iterates over the results. This function is apparently "notoriously inefficient" so calling it every frame to get a result that could (and probably should) be generated once and then cached seems like a pretty quick fix to save some CPU cycles.

I've made this change in WarpShip, but haven't gotten around to submitting it as a pull request for this one yet, sorry about that. But I thought I'd at least mention it."

Should help with frame-rate issues. The IXS Enterprise mod already has this implemented.
Link to where "notoriously inefficient" comes from : http://answers.unity3d.com/questions/547539/how-does-findgameobjectswithtag-work.html

**Comment by BobPalmer** [comment]
Already fixed that one - turns out there was another issue, got that one sorted.
