### ISSUE TITLE
Problem using Heavy, Folding and 1.25 meter drives

### ISSUE THREAD

**Issue by JEMorello** [UmbraSpaceIndustries/WarpDrive#29]
Every time I load the mod, these don't have working interface even in build mode as the 2.5 meter and .625 meter drives do. Seems somehow a pieces is missing or not connecting the parts andd specs t the system.

**Comment by helaeon** [comment]
Are these the ZZZ drives that I made a cfg port for back around 1.0?
I haven't done anything with those configs for 1.1 and I don't have the tools to make any changes to ZZZ's models that may be necessary for 1.1.
The official parts are the .625m and 2.5m drives that come with the package RoverDude releases.

**Comment by JEMorello** [comment]
So, if that is the case, are these other parts adjusttable via cfg to match the pattern of the curently working parts? or are the working ones only so due to MM code?

**Comment by helaeon** [comment]
The working ones are the official parts. So no MM code is needed, and those parts are the ones to pattern off.
Keep in mind that the folding drives were made by someone else (ZZZ, not RoverDude), so use my old configs to give you an idea of the animation names to call in the cfg. However, I fear that changes may be needed to the models. Those models were made pre-KSP .23 for KSP Interstellar for the first Alcubierre Drive in KSP that FractalUK made.
I honestly haven't taken a look at it for 1.1. Those configs you have were an unofficial port that was reasonably easy at the time. You're welcome to poke at it and see if you can get them working via config changes. I'd alter the cfgs themselves and not worry about making a MM patch.

**Comment by JEMorello** [comment]
After working to hunt them down, I found these other type are actually from KSPI, I apologize. I will close the issue, but I would like a write up on the drive workin if I could, so I have a good reference to get these working. I have time, as it appears there isn't 1.1.2 extra solar systems yet.

**Comment by JEMorello** [comment]
As noted, issue being closed as not part of relevant mod.
