### ISSUE TITLE
Problem With Download

### ISSUE THREAD

**Issue by TheDerpSquid1** [UmbraSpaceIndustries/WarpDrive#39]
When I download it the mod doesn't show up in-game, and when I try to re-download it the mod still doesn't work. I download it to
_C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\Squad_
And yes, I unzipped the folder to the same location. Can someone help? I will attach the zip folder just in case.
[WarpDrive_0.5.4.0.zip](https://github.com/BobPalmer/WarpDrive/files/788839/WarpDrive_0.5.4.0.zip)

**Comment by BobPalmer** [comment]
Installation error.  Put the contents of GameData in the zip into your GameData folder in your KSP folder.
