### ISSUE TITLE
Different Fuel Types

### ISSUE THREAD

**Issue by Donziboy2** [UmbraSpaceIndustries/WarpDrive#5]
Could we get a fuel switch to use say LH2?

**Comment by helaeon** [comment]
Would a Module Manager patch be sufficient?

**Comment by BobPalmer** [comment]
For this, I'd prefer folks to use MM.   Definitely not LH2 because it removes all limits from using the drive.  I would be more open to letting it use alternate noble gasses.

**Comment by Donziboy2** [comment]
My big grip with xenon is the lack of access.  If I want fuel I have to launch it from Kerbin.

**Comment by BobPalmer** [comment]
That is precisely the point.

**Comment by Donziboy2** [comment]
Only if your playing career, which as long as you don't go broke is not a limit, with sandbox its just boring.

**Comment by BobPalmer** [comment]
Feel free to edit your own config, but closing this as its not happening in the core mod.
